version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 7341:7341
    volumes:
      - .:/usr/share/nginx/dashboard
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
